package compforge

import (
	"fmt"
	"strings"
)

func generateBash(spec *Spec) (string, error) {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Bash completion for %s\n", spec.Name))
	b.WriteString(fmt.Sprintf("# Auto-generated by compforge on %s\n", FormatDate()))
	b.WriteString(fmt.Sprintf("# %s\n\n", spec.Description))

	b.WriteString(fmt.Sprintf("_%s_completion() {\n", spec.Name))
	b.WriteString("    local cur prev opts\n")
	b.WriteString("    COMPREPLY=()\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n\n")

	// Build command list
	b.WriteString("    local commands=")
	b.WriteString(buildBashCommands(spec.Commands, spec.Name))
	b.WriteString("\n\n")

	// Handle options per command
	b.WriteString("    case \"${COMP_WORDS[1]}\" in\n")
	for _, cmd := range spec.Commands {
		b.WriteString("        ")
		if cmd.Name != "" {
			b.WriteString(cmd.Name)
			for _, alias := range cmd.Aliases {
				if alias != "" {
					b.WriteString("|")
					b.WriteString(alias)
				}
			}
		}
		b.WriteString(")\n")
		writeBashCmdOptions(&b, cmd, spec.Name)
		b.WriteString("            ;;\n")
	}
	b.WriteString("        *)\n            # No command selected, complete with main commands\n")
	b.WriteString("            COMPREPLY=( $(compgen -W \"${commands}\" -- ${cur}) )\n")
	b.WriteString("            ;;\n")
	b.WriteString("    esac\n\n")

	b.WriteString("    return 0\n")
	b.WriteString("}\n\n")

	b.WriteString("complete -F _" + spec.Name + "_completion " + spec.Name)
	for _, cmd := range spec.Commands {
		b.WriteString(" " + cmd.Name)
	}
	b.WriteString("\n")

	return b.String(), nil
}

func writeBashCmdOptions(b *strings.Builder, cmd CLICommand, rootName string) {
	// Handle options with choices (e.g., --status active|pending|done)
	for _, opt := range cmd.Options {
		if len(opt.Choices) > 0 {
			b.WriteString("        if [[ ${prev} == " + opt.Name + " ]]; then\n")
			b.WriteString("            local choices=" + buildBashChoices(opt.Choices) + "\n")
			b.WriteString("            COMPREPLY=( $(compgen -W \"${choices}\" -- ${cur}) )\n")
			b.WriteString("            return 0\n")
			b.WriteString("        fi\n")
		}
	}

	// Handle subcommands
	if len(cmd.SubCommands) > 0 {
		b.WriteString("        local subcommands=" + buildBashSubCommands(cmd.SubCommands) + "\n")
		b.WriteString("        COMPREPLY=( $(compgen -W \"${subcommands}\" -- ${cur}) )\n")
	}
}

func buildBashCommands(commands []CLICommand, rootName string) string {
	var cmds []string
	for _, cmd := range commands {
		cmds = append(cmds, cmd.Name)
		for _, alias := range cmd.Aliases {
			cmds = append(cmds, alias)
		}
	}
	return "\"" + strings.Join(cmds, " ") + "\""
}

func buildBashSubCommands(commands []CLICommand) string {
	var cmds []string
	for _, cmd := range commands {
		cmds = append(cmds, cmd.Name)
		for _, alias := range cmd.Aliases {
			cmds = append(cmds, alias)
		}
	}
	return "\"" + strings.Join(cmds, " ") + "\""
}

func buildBashChoices(choices []string) string {
	return "\"" + strings.Join(choices, " ") + "\""
}