package compforge

import (
	"fmt"
	"strings"
)

func generateZsh(spec *Spec) (string, error) {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# zsh completion for %s\n", spec.Name))
	b.WriteString(fmt.Sprintf("# Auto-generated by compforge on %s\n", FormatDate()))
	b.WriteString(fmt.Sprintf("# %s\n\n", spec.Description))

	b.WriteString(fmt.Sprintf("_%s() {\n", spec.Name))
	b.WriteString("    local -a commands\n")
	b.WriteString("    local -a options\n")
	b.WriteString("    local -a subcommands\n\n")

	// Define commands
	b.WriteString("    commands=(")
	for _, cmd := range spec.Commands {
		b.WriteString(cmd.Name + " ")
	}
	b.WriteString(")\n\n")

	// Define options
	b.WriteString("    options=(")
	for _, opt := range spec.Options {
		b.WriteString("--" + opt.Name)
		if opt.Shorthand != "" {
			b.WriteString("(-" + opt.Shorthand + ")")
		}
		if opt.Description != "" {
			b.WriteString(": " + opt.Description)
		}
		b.WriteString(" ")
	}
	b.WriteString(")\n\n")

	// Handle subcommands per command
	b.WriteString("    if [ $CURRENT -le 2 ]; then\n")
	b.WriteString("        _values 'command' ${commands[@]}\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")

	for _, cmd := range spec.Commands {
		b.WriteString("    if [ \"${words[2]}\" = \"" + cmd.Name + "\" ]; then\n")
		// Options with choices
		for _, opt := range cmd.Options {
			if len(opt.Choices) > 0 {
				b.WriteString("        if [ \"${words[$CURRENT-1]}\" = \"" + opt.Name + "\" ]; then\n")
				b.WriteString("            _values 'value' " + strings.Join(opt.Choices, " ") + "\n")
				b.WriteString("            return\n")
				b.WriteString("        fi\n")
			}
		}
		// Subcommands
		if len(cmd.SubCommands) > 0 {
			b.WriteString("        local -a subcmds=")
			for _, sub := range cmd.SubCommands {
				b.WriteString(sub.Name + " ")
			}
			b.WriteString("\n")
			b.WriteString("        _values 'subcommand' ${subcmds[@]}\n")
		}
		b.WriteString("        return\n")
		b.WriteString("    fi\n\n")
	}

	b.WriteString("    _values 'command' ${commands[@]}\n")
	b.WriteString("}\n\n")
	b.WriteString("if [[ $zsh_eval_context[-1] != 2 ]]; then\n")
	b.WriteString("    compdef _" + spec.Name + " " + spec.Name + "\n")
	b.WriteString("fi\n")

	return b.String(), nil
}

func generateFish(spec *Spec) (string, error) {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Fish shell completion for %s\n", spec.Name))
	b.WriteString(fmt.Sprintf("# Auto-generated by compforge on %s\n", FormatDate()))
	b.WriteString(fmt.Sprintf("# %s\n\n", spec.Description))

	b.WriteString("function __" + spec.Name + "_complete\n")
	b.WriteString("    set -l command (commandline -t)\n\n")

	// Commands
	b.WriteString("    set -l commands ")
	for _, cmd := range spec.Commands {
		b.WriteString(cmd.Name + " ")
	}
	b.WriteString("\n")

	// Options
	b.WriteString("    set -l options ")
	for _, opt := range spec.Options {
		b.WriteString("--" + opt.Name)
		if opt.Shorthand != "" {
			b.WriteString(" -" + opt.Shorthand)
		}
		b.WriteString(" ")
	}
	b.WriteString("\n")

	// Handle subcommands per command
	for _, cmd := range spec.Commands {
		b.WriteString(fmt.Sprintf("    if test \"$command\" = \"%s\"\n", cmd.Name))
		// Options with choices
		for _, opt := range cmd.Options {
			if len(opt.Choices) > 0 {
				b.WriteString(fmt.Sprintf("        if test (commandline -ct) = \"%s\"\n", opt.Name))
				b.WriteString("            set -l opts ")
				for _, c := range opt.Choices {
					b.WriteString(c + " ")
				}
				b.WriteString("\n")
				b.WriteString("            _fish_complete_string $opts\n")
				b.WriteString("            return\n")
				b.WriteString("        end\n")
			}
		}
		b.WriteString("        set -l subcmds ")
		for _, sub := range cmd.SubCommands {
			b.WriteString(sub.Name + " ")
		}
		b.WriteString("\n")
		b.WriteString("        _fish_complete_string $subcmds\n")
		b.WriteString("        return\n")
		b.WriteString("    end\n\n")
	}

	b.WriteString("    _fish_complete_string $commands\n")
	b.WriteString("end\n\n")

	b.WriteString(fmt.Sprintf("complete -c %s -f -n '__fish_seen_subcommand_from'", spec.Name))
	for _, cmd := range spec.Commands {
		b.WriteString(fmt.Sprintf(" %s", cmd.Name))
	}
	b.WriteString("\n")

	for _, cmd := range spec.Commands {
		b.WriteString(fmt.Sprintf("complete -c %s -f -n '__fish_seen_subcommand_from %s' -a '", spec.Name, cmd.Name))
		for _, sub := range cmd.SubCommands {
			b.WriteString(sub.Name + " ")
		}
		b.WriteString("'\n")
	}

	return b.String(), nil
}

func generatePowerShell(spec *Spec) (string, error) {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# PowerShell completion for %s\n", spec.Name))
	b.WriteString(fmt.Sprintf("# Auto-generated by compforge on %s\n", FormatDate()))
	b.WriteString(fmt.Sprintf("# %s\n\n", spec.Description))

	b.WriteString(fmt.Sprintf("Register-ArgumentCompleter -CommandName '%s' -ScriptBlock {\n", spec.Name))
	b.WriteString("    param($CommandName, $ParameterName, $WordToComplete, $CommandAst, $FakeBoundParameters)\n\n")

	// Build completions list
	cmds := []string{}
	for _, cmd := range spec.Commands {
		cmds = append(cmds, "'"+cmd.Name+"'")
	}

	b.WriteString("    $completions = @(\n")
	for _, c := range cmds {
		b.WriteString(fmt.Sprintf("        [System.Management.Automation.CompletionResult]::new(%s, '%s', 'ParameterValue', 'Command')\n", c, c))
	}
	b.WriteString("    )\n\n")

	// Options
	b.WriteString("    $options = @(\n")
	for _, opt := range spec.Options {
		b.WriteString(fmt.Sprintf("        '--%s'", opt.Name))
		if opt.Shorthand != "" {
			b.WriteString(fmt.Sprintf(", '-%s'", opt.Shorthand))
		}
		b.WriteString("\n")
	}
	b.WriteString("    )\n\n")

	b.WriteString("    $all = @($completions, $options)\n")
	b.WriteString(fmt.Sprintf("    $all | Where-Object { $_.CompletionText -like '*$WordToComplete*' } | ForEach-Object { $_ }\n"))
	b.WriteString("}\n")

	return b.String(), nil
}
